package com.liulu.networkDisk.mapper;

import com.liulu.networkDisk.model.DiskFileModel;

public interface DiskFileModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk_file
     *
     * @mbggenerated
     */
    int insert(DiskFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk_file
     *
     * @mbggenerated
     */
    int insertSelective(DiskFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk_file
     *
     * @mbggenerated
     */
    DiskFileModel selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DiskFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disk_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DiskFileModel record);
}