--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 11.0.1106
--  Created On : 星期六, 30 三月, 2019 
--  DBMS       : MySql 
--  -------------------------------------------------- 

DROP TABLE IF EXISTS disk_folder CASCADE
;

CREATE TABLE disk_folder
(
	user_dir_id NVARCHAR(36) NOT NULL  COMMENT '文件夹名称',
	dir_name NVARCHAR(200) NOT NULL  COMMENT '文件夹名称',
	parent_id NVARCHAR(36) NULL  COMMENT '文件夹父id',
	son_id NVARCHAR(36) NULL  COMMENT '子文件夹id',
	create_time DATE NULL  COMMENT '创建时间',
	update_time DATE NULL  COMMENT '更新时间',
	file_number INT NULL   COMMENT '文件数量',
	dir_size INT NULL   COMMENT '文件夹大小',
	delete_time DATE NULL   COMMENT '删除时间',
	is_delete CHAR(10) NULL   COMMENT '是否删除 1删除，默认是0',
	user_id NVARCHAR(36) NULL  COMMENT '创建人',
	PRIMARY KEY (user_dir_id)

)  COMMENT='文件夹'


